package kh.chaptes10_Exception.exception.tryCatch.run;

import kh.chaptes10_Exception.exception.tryCatch.controller.TryCatchTest;

public class Main {

	public static void main(String[] args) {
		// try-catch 테스트

		TryCatchTest tct = new TryCatchTest();

////		tct.methodA();
		tct.ioTest1();
		tct.ioTest2();
		
		
		
	}

	
	
	
	
	
	
	
}
